Add ability for toggle parameter to be a variable
nguyenquyhy/Flight-Tracker-StreamDeck pull request #100
Opened 2020-12-19 00:10 UTC by gitmitch

When triggering a SimConnect event from a generic toggle, this PR adds the ability to pass the value of a SimConnect variable as the parameter. Before, the parameter had to be a constant.

2020-12-28 12:07 UTC, nguyenquyhy requested changes

2020-12-28 12:07 UTC, nguyenquyhy commented on FlightStreamDeck.Core/Structs.cs
> +        HEADING_BUG_SET,
Do you mind removing this as I happen to add the same one? Maybe rebase on latest master branch.

2020-12-30 12:04 UTC, nguyenquyhy commented
I have manually merged this.

2020-12-30 12:04 UTC, closed without merging

2021-01-01 03:42 UTC, gitmitch commented
Thanks for taking care of this. I was away from my computer for a while. And thanks for this awesome integration between MSFS and Stream Deck! Lots of fun.